# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Piecewise Linear Interpolation for pnorm
#' @description
#' Performs linear interpolation of \code{\link{pnorm}}. See the README
#' at \url{https://github.com/yixuan/fastncdf} for details.
#'
#' The \code{fastpnorm_preallocated} version is faster if one has
#' vector of the same length already.
#'
#' @param q vector of quantiles.
#' @param p pector vector outputs (probabilities). Needs to have the same
#' length as \code{q}.
#' @param precise_tail logical for whether to use \code{\link{pnorm}} in
#' the tail.
#' @param use_cubic true if monotone cubic interpolation using Fritsch–Carlson
#' method should be used.
#' @param n_threads number of threads to use.
#' @export
#'
#' @examples
#' x <- seq(-6, 6, by = 1e-6)
#' system.time(y <- pnorm(x))
#' system.time(fasty <- fastpnorm(x))
#' all.equal(y, fasty) # tiny error
fastpnorm <- function(q, precise_tail = FALSE, use_cubic = FALSE, n_threads = 1L) {
    .Call(`_fastncdf_fastpnorm`, q, precise_tail, use_cubic, n_threads)
}

#' @rdname fastpnorm
#' @export
fastpnorm_preallocated <- function(q, p, precise_tail = FALSE, use_cubic = FALSE, n_threads = 1L) {
    invisible(.Call(`_fastncdf_fastpnorm_preallocated`, q, p, precise_tail, use_cubic, n_threads))
}

